### ISSUE TITLE
v7 Support

### ISSUE THREAD

**Issue by stuartbray-linney** [leekelleher/umbraco-opengraph#1]
Hi Leekelleher,
Thanks for writing this package, it looks awesome.
I've had an enquiry about getting something like this running on a v7 umbraco, which looks like it isn't supported yet. Is it worth me trying to install and attempt to make work on v7, or do you reckon there are better alternatives.
Thanks for your time, keep up the good work.
Cheers.

**Comment by leekelleher** [comment]
Hi @stuartbray-linney, thanks for getting in touch.

I have no plans for migrating this data-type over to v7. I'd originally developed it for a specific client-project, then later open-sourced it.  To be honest, I've never used it since.

The code is MIT licensed, so you are free to do as you like with it.

As for alternatives, I did see this package, but I've never used it, so not sure.
https://our.umbraco.org/projects/backoffice-extensions/ctaopengraphurl-property-editors/

Cheers, Lee.

**Comment by stuartbray-linney** [comment]
Cheers, I’ll look into those.
